### ISSUE TITLE
Datatype of Text in export to Excel

### ISSUE THREAD

**Issue by JosHennen** [DocxFactory/DocxFactory#17]
Hi, not sure if anyone is active on this forum but I will take my chances.
I am writing data to XLSX which is coming from a table where the field is defined as text (CHARACTER).
The cell type in Excel also turns into TEXT which implies that you cannot type a formula in such a cell.
Is there a way to tell DocXfactory to use the "General" datatype in XLSX instead of "Text"?
Thanks for any suggestions.

**Comment by alonblich** [comment]
Hello Jos,

I saw your question. Please feel free to contact me directly at alon.blich@akioma.de or alonblich@gmail.com.

As you know, you can add formulas manually in the Excel template but you can also add formulas programmatically using the ttMeta temp-table.

You can enter Excel formulas using Excel syntax and functions but you can also use 4gl/abl buffer-field or calculated field names in formulas.

You can also reference a column previous row by adding :PrevRow option to the field name. The following options are also supported - :NextRow,:PrevCol,:NextCol.

Please have a look at the create_template_ttmeta.p procedure in the <DocxFactory installation dir>\progress\samples\src\excel directory.

Hope this helps!
Alon
